# -*- mode: python -*-

Import("env")

env.Library(
    target='view',
    source=[
        'view.cpp',
        'view_catalog.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline'
    ]
)
