# -*- mode: python -*-

Import("env")

env.Library(
    target='view_mongod',
    source=[
        'view_catalog.cpp',
        'view_sharding_check.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'view_shared',
    ]
)

env.Library(
    target='view_shared',
    source=[
        'view.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ]
)
