# -*- mode: python -*-

Import("env")

env.Library(
    target= 'timeseries',
        source=[
            'timeseries.cpp',
            'timeseries_monitor.cpp',
    ],
     LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/service_context',
    ]
)