# -*- mode: python -*-

Import("env")

env.Library(
    target= 'timeseries',
        source=[
            'timeseries.cpp',
    ],
     LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ]
)

env.CppUnitTest(
        target='timeseries_test',
        source=[
            'timeseries_test.cpp',
        ],
        LIBDEPS=[
            '$BUILD_DIR/mongo/base',
            '$BUILD_DIR/mongo/db/timeseries/timeseries'
        ],
)