# -*- mode: python -*-

Import("env")

env.CppUnitTest(
        target='timeseries_test',
        source=[
            'timeseries.cpp',
            'timeseries_test.cpp',
        ],
        LIBDEPS=[
            '$BUILD_DIR/mongo/base',
        ],
)